server {
  listen 80;
  server_name _;

  location = /proxy.pac {
    root /usr/share/nginx/html;
    default_type application/x-ns-proxy-autoconfig;
    add_header Cache-Control "no-cache";
  }

  location / {
    return 404;
  }
}
